# Generated by Django 3.2.5 on 2021-08-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_user_userprofileinfo_love'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='love',
            new_name='user',
        ),
    ]
