# Generated by Django 3.2.5 on 2021-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_rename_love_userprofileinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
