# Generated by Django 3.2.5 on 2021-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user',
            new_name='penguna',
        ),
    ]
